services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        ports:
            - 3306:$MYSQL_PORT
        volumes:
            - mysql_data:/var/lib/mysql
    redis:
        image: redis:latest
        ports:
            - 6379:$REDIS_PORT
        volumes:
            - redis_data:/data
    localstack:
        image: localstack/localstack
        ports:
            - '4566:4566'
            - '4572:4572'
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=us-east-1
            - DATA_DIR=/tmp/localstack/data
volumes:
    mysql_data:
    redis_data:
    localstack_data:
