version: '3.8'

services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        ports:
            - 3306:$MYSQL_PORT
        volumes:
            - mysql_data:/var/lib/mysql
    redis:
        image: redis:latest
        ports:
            - 6379:$REDIS_PORT
        volumes:
            - redis_data:/data
    minio:
        image: minio/minio:latest
        volumes:
            - minio_data:/data
        ports:
            - '9000:9000'
        environment:
            MINIO_ROOT_USER: $AWS_S3_API_KEY_ID
            MINIO_ROOT_PASSWORD: $AWS_S3_API_SECRET
            MINIO_DEFAULT_BUCKETS: $AWS_S3_BUCKET_NAME
            AWS_DEFAULT_REGION: $AWS_S3_REGION
        command: server /data
volumes:
    mysql_data:
    redis_data:
    minio_data:
